/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type OpportunityStage = "closed_lost" | "closed_won" | "negotiation" | "proposal" | "prospecting" | "qualification";

export type TenantRole = "admin" | "member" | "owner";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Accounts {
  address_line1: string | null;
  address_line2: string | null;
  city: string | null;
  country: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  email: string | null;
  id: Generated<string>;
  industry: string | null;
  name: string;
  notes: string | null;
  owner_id: string;
  phone: string | null;
  postal_code: string | null;
  region: string | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  website: string | null;
}

export interface Contacts {
  account_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  email: string | null;
  first_name: string;
  id: Generated<string>;
  job_title: string | null;
  last_name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface FieldDefinitions {
  api_name: string;
  created_at: Generated<Timestamp>;
  default_value: string | null;
  description: string | null;
  field_type: string;
  id: Generated<string>;
  is_system: Generated<boolean>;
  label: string;
  object_id: string;
  options: Generated<Json | null>;
  required: Generated<boolean>;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface LayoutDefinitions {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  layout_type: string;
  name: string;
  object_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface LayoutFields {
  field_id: string;
  id: Generated<string>;
  layout_id: string;
  section: Generated<number>;
  section_label: string | null;
  sort_order: Generated<number>;
  tenant_id: string;
  visible_to_roles: string[] | null;
  width: Generated<string | null>;
}

export interface LeadConversionMappings {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  lead_field_api_name: string;
  target_field_api_name: string;
  target_object: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ObjectDefinitions {
  api_name: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  icon: string | null;
  id: Generated<string>;
  is_system: Generated<boolean>;
  label: string;
  name_field_id: string | null;
  name_template: string | null;
  owner_id: string;
  plural_label: string;
  sort_order: Generated<number>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface ObjectPermissions {
  can_create: Generated<boolean>;
  can_delete: Generated<boolean>;
  can_read: Generated<boolean>;
  can_update: Generated<boolean>;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  object_id: string;
  role: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Opportunities {
  account_id: string | null;
  created_at: Generated<Timestamp>;
  created_by: string;
  currency: string | null;
  description: string | null;
  expected_close_date: Timestamp | null;
  id: Generated<string>;
  owner_id: string;
  stage: Generated<OpportunityStage>;
  stage_history: Generated<Json>;
  tenant_id: string;
  title: string;
  updated_at: Generated<Timestamp>;
  value: Numeric | null;
}

export interface Organisations {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  name: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface PageLayouts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  layout: Json;
  name: string;
  object_id: string;
  published_at: Timestamp | null;
  published_layout: Json | null;
  role: string | null;
  status: Generated<string>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  version: Generated<number>;
}

export interface PageLayoutVersions {
  id: Generated<string>;
  layout: Json;
  layout_id: string;
  published_at: Generated<Timestamp>;
  published_by: string | null;
  tenant_id: string;
  version: number;
}

export interface PipelineDefinitions {
  api_name: string;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  is_default: Generated<boolean>;
  is_system: Generated<boolean>;
  name: string;
  object_id: string;
  owner_id: string;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
}

export interface RecordRelationships {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  relationship_id: string;
  source_record_id: string;
  target_record_id: string;
  tenant_id: string;
}

export interface Records {
  created_at: Generated<Timestamp>;
  current_stage_id: string | null;
  field_values: Generated<Json>;
  id: Generated<string>;
  name: string;
  object_id: string;
  owner_id: string;
  owner_name: string | null;
  owner_record_id: string | null;
  pipeline_id: string | null;
  stage_entered_at: Timestamp | null;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  updated_by_name: string | null;
  updated_by_record_id: string | null;
}

export interface RelationshipDefinitions {
  api_name: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  label: string;
  relationship_type: string;
  required: Generated<boolean>;
  reverse_label: string | null;
  source_object_id: string;
  target_object_id: string;
  tenant_id: string;
}

export interface SalesTargets {
  created_at: Generated<Timestamp | null>;
  created_by: string | null;
  currency: Generated<string | null>;
  id: Generated<string>;
  period_end: Timestamp;
  period_start: Timestamp;
  period_type: string;
  target_entity_id: string | null;
  target_type: string;
  target_value: Numeric;
  tenant_id: string;
  updated_at: Generated<Timestamp | null>;
}

export interface SchemaMigrations {
  applied_at: Generated<Timestamp>;
  filename: string;
}

export interface StageDefinitions {
  api_name: string;
  colour: Generated<string>;
  created_at: Generated<Timestamp>;
  default_probability: number | null;
  description: string | null;
  expected_days: number | null;
  id: Generated<string>;
  name: string;
  pipeline_id: string;
  sort_order: number;
  stage_type: Generated<string>;
  tenant_id: string;
}

export interface StageGates {
  error_message: Generated<string | null>;
  field_id: string;
  gate_type: Generated<string>;
  gate_value: string | null;
  id: Generated<string>;
  stage_id: string;
  tenant_id: string;
}

export interface StageHistory {
  changed_at: Generated<Timestamp>;
  changed_by: string;
  days_in_previous_stage: number | null;
  from_stage_id: string | null;
  id: Generated<string>;
  pipeline_id: string;
  record_id: string;
  tenant_id: string;
  to_stage_id: string;
}

export interface TeamMembers {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  role: Generated<string>;
  team_id: string;
  tenant_id: string;
  user_id: string;
}

export interface Teams {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  owner_id: string;
  tenant_id: string;
}

export interface TenantMemberships {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  organisation_id: string | null;
  role: Generated<TenantRole>;
  tenant_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Tenants {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  plan: Generated<string | null>;
  settings: Generated<Json | null>;
  slug: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface UserProfiles {
  created_at: Generated<Timestamp>;
  display_name: string | null;
  id: Generated<string>;
  job_title: string | null;
  updated_at: Generated<Timestamp>;
  updated_by: string;
  user_id: string;
}

export interface DB {
  accounts: Accounts;
  contacts: Contacts;
  field_definitions: FieldDefinitions;
  layout_definitions: LayoutDefinitions;
  layout_fields: LayoutFields;
  lead_conversion_mappings: LeadConversionMappings;
  object_definitions: ObjectDefinitions;
  object_permissions: ObjectPermissions;
  opportunities: Opportunities;
  organisations: Organisations;
  page_layout_versions: PageLayoutVersions;
  page_layouts: PageLayouts;
  pipeline_definitions: PipelineDefinitions;
  record_relationships: RecordRelationships;
  records: Records;
  relationship_definitions: RelationshipDefinitions;
  sales_targets: SalesTargets;
  schema_migrations: SchemaMigrations;
  stage_definitions: StageDefinitions;
  stage_gates: StageGates;
  stage_history: StageHistory;
  team_members: TeamMembers;
  teams: Teams;
  tenant_memberships: TenantMemberships;
  tenants: Tenants;
  user_profiles: UserProfiles;
}
