import { Kysely, PostgresDialect } from 'kysely';
import { pool } from './client.js';
import type { DB } from './kysely.types.js';

/**
 * Kysely database instance wrapping the RLS-aware connection pool.
 *
 * The underlying pool is a Proxy that intercepts queries to set
 * `app.current_tenant_id` when a tenant context is present (see client.ts).
 * This ensures Kysely-built queries respect tenant isolation through
 * Postgres Row-Level Security policies.
 *
 * Usage:
 *   import { db } from './db/kysely.js';
 *   const accounts = await db.selectFrom('accounts').selectAll().execute();
 *
 * Type safety:
 *   The DB interface is auto-generated by kysely-codegen and reflects
 *   the current database schema. Re-run `npm run db:types` after migrations.
 */
export const db = new Kysely<DB>({
  dialect: new PostgresDialect({ pool }),
});
